config/routes.rb
TestForBodyroom::Application.routes.draw do
  resources :notes

  match "admin/index", to: "admin#index", via: "get"
  match "admin/edit_file", to: "admin#edit_file", via: "get"
  match "admin/show_file", to: "admin#show_file", via: "post"
  match "admin/save_file", to: "admin#save_file", via: "post"

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :admin_user

  def index
      
  end

  def edit_file
    @content = ""
    @file_path = ""
  end

  def show_file

    @file_path = params[:file_path]
      
    if (File.exist?(@file_path))
      file = File.open(@file_path)
      @file_content = file.read()
      file.close()
      flash.now[:notice] = "Файл открыт"
    else
      file = File.new(@file_path, "w")
      @file_content = ""
      flash.now[:notice] = "Файл создан"
    end

    render "edit_file"

  end

  def save_file
    @file_path = params[:file_path]
    @file_content = params[:file_content]

    file = File.open(@file_path, "w")  
    file.write(@file_content)     
    file.close()

    flash.now[:notice] = "Данные сохранены"

    render "edit_file"
    
  end

  private

    def admin_user  
      #redirect_to(root_url) unless signed_in?
      #redirect_to(root_url) unless current_user().admin?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :set_note, only: [:show, :destroy]

  # GET /notes.json
  def index
    @notes = Note.all 
  end

  # GET /notes/1.json
  def show    

  end

  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.json { head :no_content, status: 204 }
    end
  end

  private
    
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/admin/edit_file.html.erb
<br /><br />
<h1><%= flash[:notice] %></h1>

<%= form_tag( {action: "show_file"} ) do  %>

  <%= text_field_tag(:file_path, @file_path, size: "100") %><br />

  <%= submit_tag("Открыть") %>

<% end %>


<%= form_tag( {action: "save_file"} ) do  %>

  <%= text_area_tag(:file_content, @file_content, size: "74x40") %><br />

  <%= hidden_field_tag(:file_path, @file_path, size: "100") %>

  <%= submit_tag("Сохранить") %>

<% end %>

app/views/admin/index.html.erb
<br /><br />
<h1>Зона администратора</h1>

<ul>
  <li><%= link_to("Редактор исходных файлов проекта", admin_edit_file_path) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestForBodyroom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>